"""initial schema

Revision ID: f4385e61a75c
Revises: 
Create Date: 2026-08-03 14:51:20.739973
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4385e61a75c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=128), nullable=True),
    sa.Column('sanitized_details', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_table('batch_scan_runs',
    sa.Column('child_scan_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partial', 'failed', 'cancelled', name='runstatus', native_enum=False), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_scan_runs'))
    )
    op.create_table('canonical_jobs',
    sa.Column('normalized_company', sa.String(length=255), nullable=False),
    sa.Column('normalized_title', sa.String(length=255), nullable=False),
    sa.Column('normalized_location', sa.String(length=255), nullable=False),
    sa.Column('canonical_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('primary_source_job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'possibly_closed', 'closed', 'incomplete', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_jobs')),
    sa.UniqueConstraint('canonical_fingerprint', name=op.f('uq_canonical_jobs_canonical_fingerprint'))
    )
    op.create_table('daily_reports',
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_reports')),
    sa.UniqueConstraint('report_date', name=op.f('uq_daily_reports_report_date'))
    )
    op.create_table('job_preferences',
    sa.Column('allowed_categories', sa.JSON(), nullable=False),
    sa.Column('auto_send_categories', sa.JSON(), nullable=False),
    sa.Column('forbidden_categories', sa.JSON(), nullable=False),
    sa.Column('allowed_cities', sa.JSON(), nullable=False),
    sa.Column('remote_allowed', sa.Boolean(), nullable=False),
    sa.Column('minimum_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('allowed_schedules', sa.JSON(), nullable=False),
    sa.Column('forbidden_schedules', sa.JSON(), nullable=False),
    sa.Column('willing_without_experience', sa.Boolean(), nullable=False),
    sa.Column('consider_outside_primary_resume', sa.Boolean(), nullable=False),
    sa.Column('language_constraints', sa.JSON(), nullable=False),
    sa.Column('maximum_daily_applications', sa.Integer(), nullable=False),
    sa.Column('minimum_auto_send_score', sa.Integer(), nullable=False),
    sa.Column('additional_rules', sa.JSON(), nullable=False),
    sa.Column('auto_send_enabled', sa.Boolean(), nullable=False),
    sa.Column('global_pause', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_preferences'))
    )
    op.create_table('job_sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('adapter_type', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('health_status', sa.Enum('unknown', 'healthy', 'degraded', 'paused', 'disabled', name='sourcehealth', native_enum=False), nullable=False),
    sa.Column('last_scan_status', sa.Enum('queued', 'running', 'succeeded', 'partial', 'failed', 'cancelled', name='runstatus', native_enum=False), nullable=True),
    sa.Column('automatic_actions_paused', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_sources'))
    )
    op.create_table('oauth_credentials',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('encrypted_refresh_token', sa.LargeBinary(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('token_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_credentials')),
    sa.UniqueConstraint('provider', name=op.f('uq_oauth_credentials_provider'))
    )
    op.create_table('resumes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes')),
    sa.UniqueConstraint('sha256', name=op.f('uq_resumes_sha256')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_resumes_storage_key'))
    )
    op.create_table('user_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('work_experience', sa.JSON(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('driving_licences', sa.JSON(), nullable=False),
    sa.Column('confirmed_facts', sa.JSON(), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    op.create_table('alerts',
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('safe_diagnostics', sa.JSON(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], name=op.f('fk_alerts_source_id_job_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_table('scan_runs',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('scan_type', sa.Enum('full', 'incremental', 'recheck', name='scantype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partial', 'failed', 'cancelled', name='runstatus', native_enum=False), nullable=False),
    sa.Column('discovered_categories', sa.Integer(), nullable=False),
    sa.Column('scanned_entrypoints', sa.Integer(), nullable=False),
    sa.Column('scanned_pages', sa.Integer(), nullable=False),
    sa.Column('found_jobs', sa.Integer(), nullable=False),
    sa.Column('new_jobs', sa.Integer(), nullable=False),
    sa.Column('updated_jobs', sa.Integer(), nullable=False),
    sa.Column('unchanged_jobs', sa.Integer(), nullable=False),
    sa.Column('parsing_errors', sa.Integer(), nullable=False),
    sa.Column('network_errors', sa.Integer(), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('diagnostics', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], name=op.f('fk_scan_runs_source_id_job_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_runs'))
    )
    op.create_table('source_categories',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('parent_category_id', sa.Uuid(), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['source_categories.id'], name=op.f('fk_source_categories_parent_category_id_source_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], name=op.f('fk_source_categories_source_id_job_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_categories')),
    sa.UniqueConstraint('source_id', 'external_id', 'locale', name='uq_source_category_identity')
    )
    op.create_table('source_jobs',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_job_id', sa.Uuid(), nullable=True),
    sa.Column('external_job_id', sa.String(length=255), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('localized_urls', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=500), nullable=True),
    sa.Column('employer_url', sa.String(length=2048), nullable=True),
    sa.Column('categories_seen', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('salary_text', sa.String(length=500), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('cities', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=255), nullable=True),
    sa.Column('required_experience', sa.String(length=255), nullable=True),
    sa.Column('no_experience', sa.Boolean(), nullable=True),
    sa.Column('workplace_type', sa.String(length=32), nullable=True),
    sa.Column('public_email', sa.String(length=320), nullable=True),
    sa.Column('public_phone', sa.String(length=64), nullable=True),
    sa.Column('application_url', sa.String(length=2048), nullable=True),
    sa.Column('page_locale', sa.String(length=16), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'possibly_closed', 'closed', 'incomplete', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('confirmed_absence_count', sa.Integer(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['canonical_jobs.id'], name=op.f('fk_source_jobs_canonical_job_id_canonical_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], name=op.f('fk_source_jobs_source_id_job_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_jobs')),
    sa.UniqueConstraint('source_id', 'external_job_id', name='uq_source_job_external')
    )
    op.create_index('ix_source_jobs_content_hash', 'source_jobs', ['content_hash'], unique=False)
    op.create_index('ix_source_jobs_status_last_checked', 'source_jobs', ['status', 'last_checked_at'], unique=False)
    op.create_table('employer_contacts',
    sa.Column('canonical_job_id', sa.Uuid(), nullable=False),
    sa.Column('source_job_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('contact_type', sa.Enum('email', 'application_url', 'internal_job_board', name='contacttype', native_enum=False), nullable=False),
    sa.Column('discovery_source', sa.String(length=128), nullable=False),
    sa.Column('official_domain', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'rejected', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['canonical_jobs.id'], name=op.f('fk_employer_contacts_canonical_job_id_canonical_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_job_id'], ['source_jobs.id'], name=op.f('fk_employer_contacts_source_job_id_source_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employer_contacts'))
    )
    op.create_table('job_snapshots',
    sa.Column('source_job_id', sa.Uuid(), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_job_id'], ['source_jobs.id'], name=op.f('fk_job_snapshots_source_job_id_source_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_snapshots'))
    )
    op.create_table('match_evaluations',
    sa.Column('canonical_job_id', sa.Uuid(), nullable=False),
    sa.Column('source_job_id', sa.Uuid(), nullable=False),
    sa.Column('resume_fit', sa.Integer(), nullable=False),
    sa.Column('preference_fit', sa.Integer(), nullable=False),
    sa.Column('overall_fit', sa.Integer(), nullable=False),
    sa.Column('requirements_met', sa.JSON(), nullable=False),
    sa.Column('missing_requirements', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('scam_indicators', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('decision', sa.Enum('auto_apply', 'prepare_for_review', 'skip', 'block', name='matchdecision', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_rules_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['canonical_jobs.id'], name=op.f('fk_match_evaluations_canonical_job_id_canonical_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_job_id'], ['source_jobs.id'], name=op.f('fk_match_evaluations_source_job_id_source_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_evaluations'))
    )
    op.create_table('applications',
    sa.Column('canonical_job_id', sa.Uuid(), nullable=False),
    sa.Column('source_job_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_contact_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('prepared', 'pending_review', 'approved', 'auto_approved', 'sending', 'sent', 'delivery_unknown', 'failed', 'blocked', 'cancelled', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('policy_decision', sa.Enum('auto_approved', 'pending_review', 'blocked', 'skipped', name='policydecision', native_enum=False), nullable=True),
    sa.Column('policy_result', sa.JSON(), nullable=False),
    sa.Column('used_confirmed_facts', sa.JSON(), nullable=False),
    sa.Column('content_validated', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['canonical_jobs.id'], name=op.f('fk_applications_canonical_job_id_canonical_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_contact_id'], ['employer_contacts.id'], name=op.f('fk_applications_recipient_contact_id_employer_contacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_applications_resume_id_resumes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_job_id'], ['source_jobs.id'], name=op.f('fk_applications_source_job_id_source_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('canonical_job_id', name='uq_application_canonical_job'),
    sa.UniqueConstraint('idempotency_key', name='uq_application_idempotency')
    )
    op.create_table('email_deliveries',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('sending', 'sent', 'delivery_unknown', 'temporary_failure', 'permanent_failure', name='deliverystatus', native_enum=False), nullable=False),
    sa.Column('sanitized_provider_response', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_email_deliveries_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_deliveries')),
    sa.UniqueConstraint('application_id', name=op.f('uq_email_deliveries_application_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_deliveries')
    op.drop_table('applications')
    op.drop_table('match_evaluations')
    op.drop_table('job_snapshots')
    op.drop_table('employer_contacts')
    op.drop_index('ix_source_jobs_status_last_checked', table_name='source_jobs')
    op.drop_index('ix_source_jobs_content_hash', table_name='source_jobs')
    op.drop_table('source_jobs')
    op.drop_table('source_categories')
    op.drop_table('scan_runs')
    op.drop_table('alerts')
    op.drop_table('user_profiles')
    op.drop_table('resumes')
    op.drop_table('oauth_credentials')
    op.drop_table('job_sources')
    op.drop_table('job_preferences')
    op.drop_table('daily_reports')
    op.drop_table('canonical_jobs')
    op.drop_table('batch_scan_runs')
    op.drop_table('audit_events')
    # ### end Alembic commands ###

